### ISSUE TITLE
XGBoost_data_preprocessing Error

### ISSUE THREAD

**Issue by HubertR21** [MI2-Education/2022L-WB-ML-1#10]
Nasz zbiór lisbon-houses nie jest w stanie przejść przez preprocessing dla XGBoost, pomimo zamiany na data.frame. Zbiór danych dostępny jest przy KM2 i wewnątrz naszej paczki.

`
source("./XGBoost_function.R")
source("./XGBoost_predict.R")
setwd("C:/Users/Hubert/Dropbox/Studia/Semestr VI/Warsztaty Badawcze")

data <- read.csv("C:/Users/Hubert/Dropbox/Studia/Semestr VI/Warsztaty Badawcze/archive/lisbon-houses.csv")

df <- as.data.frame(data)

preprocessed <- XGBoost_data_preprocessing(data = df, target = 'Price')

modelHouse <- XGBoost_function(df, 'Price', eta = 0.1, max_depth  = 7, nrounds=79)

preprocessed <- XGBoost_data_preprocessing(data = data, target = 'Price')

modelHouse <- XGBoost_function(data, 'Price', eta = 0.1, max_depth  = 7, nrounds=79)
`

Rzucany błąd:

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
contrasts can be applied only to factors with 2 or more levels

stop("contrasts can be applied only to factors with 2 or more levels")
`contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])
model.matrix.default(object = ~. + 0, data = structure(list(Id = c(101L, 
102L, 103L, 104L, 105L, 106L, 107L, 108L, 109L, 110L, 111L, 112L, 
113L, 114L, 115L, 116L, 117L, 118L, 119L, 120L, 121L, 122L, 123L, 
124L, 125L, 126L, 127L, 128L, 129L, 130L, 131L, 132L, 133L, 134L, ...
do.call("model.matrix.default", c(list(object = object, data = data, 
contrasts.arg = object$contrasts), dots))
model.matrix.lm(~. + 0, data = data_DT[, -c(target), with = F], 
na.action = "na.pass") at XGBoost_function.R#88
XGBoost_data_preprocessing(data, target) at XGBoost_function.R#124
XGBoost_function(data, "Price", eta = 0.1, max_depth = 7, nrounds = 79)

**Comment by WJakubowsk** [comment]
1. XGBoost_data_preprocessing zwraca listę, składającą się ze zbioru testowego i treningowego. Żeby otrzymać dane, należy napisać:
train <- XGBoost_data_preprocessing(data, "Price")$train
test <- XGBoost_data_preprocessing(data, "Price")$test

Żeby skorzystać z funkcji XGBoost_function i zbudować model, wystarczy od razu wywołać:
model <- XGBoost_function(data, "Price", ...) - funkcja wewnątrz sama wykonuje preprocessing danych i korzysta ze zbioru treningowego. 

Funkcja preprocessingu będzie przydatna wyłącznie w przypadku predykcji, kiedy to powinniśmy przed wywołaniem funkcji predict, preprocessować dane wspomnianą funkcją. 
Przydatny powinien się okazać zamieszczony przykład, obrazujący działanie z podobnym zbiorem dotyczącym predykcji cen w Kaliforni

**Comment by HubertR21** [comment]
Rozumiem, że to jest używane jedynie wewnątrz XGBoost_function, tylko pomimo zrobienia tego samego co w waszym przykładzie na naszych danych kod wyrzuca error (zrzut ekranu dla rozjaśnienia errora):
![image](https://user-images.githubusercontent.com/56126542/164502012-2f1f2092-71e7-4952-abae-3040df388c8f.png)

**Comment by WJakubowsk** [comment]
Wygląda na to, że w waszym zbiorze pojawiły się kolumny z tylko jedną wartością unikalną. Zaktualizowałem kod funkcji, możecie też po prostu zmodyfikować dane tą jedną komendą:
 
#removing features with one unique value
library(dplyr)
data <- data %>% select(where(~ n_distinct(.) > 1))

Załadowałem wasz zbiór "lisbon-houses", zadziałało po tej korekcie.

**Comment by HubertR21** [comment]
Super, wielkie dzięki , zamykam issue
