### ISSUE TITLE
XGBoostfunction train error

### ISSUE THREAD

**Issue by HubertR21** [MI2-Education/2022L-WB-ML-1#11]
W waszej funkcji XGBoost_function występuje problem logiczny, gdyż wydaje mi się, że nie da się tak naprawdę w poprawny sposób dokonać predykcji. 

W przykładzie z XGBoost_predict najpierw dokonujemy zbudowania modelu za pomocą XGBoost_function, wewnątrz czego wykonywany jest XGBoost_data_preprocessing i robi podział nr 1. Następnie wywołujemy XGBoost_data_preprocessing, aby otrzymać zbiór testowy, ale tutaj otrzymujemy podział nr 2, który jest istotnie inny niż ten pierwszy, gdyż set.seed niestety nie działa tak jak powinien.  W takim przypadku test wykonywany jest na części danych które model już widział, co nie jest pożądane.

Sugeruję, aby XGBoost_data_preprocessing było samodzielną funkcją i do XGBoost_function podajemy zbiór treningowy uzyskany za jego pomocą, a wewnątrz nie dokonujemy już kolejnego preprocessingu.

Poniżej przykład, że wywołanie XGBoost_data_preprocessing na tym samym seedzie daje różne wyniki, w tym przypadku Id różnych obserwacji:

````
> set.seed(123)
> test  <- XGBoost_data_preprocessing(data, 'Price')$test
> head(test$Id)
[1] 102 104 105 108 111 113
> test  <- XGBoost_data_preprocessing(data, 'Price')$test
> head(test$Id)
[1] 102 103 104 110 114 115
> test  <- XGBoost_data_preprocessing(data, 'Price')$test
> head(test$Id)
[1] 104 108 117 121 126 128
````

**Comment by WJakubowsk** [comment]
Faktycznie, zaktualizowałem już kod w repozytorium, podział zbioru na treningowy i testowy powinien się teraz odbywać poprawnie.

**Comment by HubertR21** [comment]
Dzięki, wydaje się że działa. Zamykam issue.
